Make assertion on checking password in SQL backend use a message
This matters because in Juno, we hit an error due to the missing message:

 [-] tuple index out of range
 Traceback (most recent call last):
   File "/usr/lib64/python2.6/site-packages/keystone/common/wsgi.py", line 223, in __call__
     result = method(context, **params)
   File "/usr/lib64/python2.6/site-packages/keystone/token/controllers.py", line 100, in authenticate
     context, auth)
   File "/usr/lib64/python2.6/site-packages/keystone/token/controllers.py", line 298, in _authenticate_local
     raise exception.Unauthorized(e.args[0])
 IndexError: tuple index out of range